jenkins:
  controller:
    ingress:
      enabled: true
      ingressClassName: haproxy
      hostName: jenkins.lab01.dev.homelab.corp
      path: /
      annotations: {}

  agent:
    websocket: true

  persistence:
    enabled: true
    storageClass: local-storage
    annotations: {}
    labels: {}
    accessMode: "ReadWriteOnce"
    size: "8Gi"
