jenkins:
  controller:
    ingress:
      enabled: true
      apiVersion: "extensions/v1beta1"
      hostName: "jenkins.lab01.dev.homelab.corp"
      annotations:
        kubernetes.io/ingress.class: "haproxy"

  agent:
    websocket: true

  persistence:
    enabled: true
    storageClass: local-storage
    annotations: {}
    labels: {}
    accessMode: "ReadWriteOnce"
    size: "8Gi"
