apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-haproxy
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/D13G02/homelab-gitops.git
    targetRevision: main
    path: platform/ingress-haproxy
    helm:
      valueFiles:
        - values/default.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true