apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: platform
  sources:
  - repoURL: https://github.com/D13G02/homelab-gitops.git
    targetRevision: main
    path: platform/metallb
    helm:
      valueFiles:
        - values/default.yaml
        - $values/clusters/dev/lab01/platform/metallb-values.yaml
  - repoURL: https://github.com/D13G02/homelab-gitops.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true