vault:
  global:
    enabled: true

  server:
    ingress:
      enabled: true
      labels: {}
      annotations: {}
      ingressClassName: "haproxy"
      pathType: Prefix
      activeService: true
      hosts:
        - host: vault.lab01.dev.homelab.corp
          paths: []
      extraPaths: []
      tls: []

    dataStorage:
      enabled: true
      size: 5Gi
      mountPath: "/vault/data"
      storageClass: local-storage
      accessMode: ReadWriteOnce
      annotations: {}
      labels: {}
