configInline:
  address-pools:
    - name: default-pool
      protocol: layer2
      addresses:
        - 192.168.50.100-192.168.50.120

frr-k8s:
  enabled: false
  prometheus:
    serviceMonitor:
      enabled: false

global:
  prometheus:
    serviceMonitor:
      enabled: false