# Configuración principal - L2 básico
configInline:
  address-pools:
    - name: default-pool
      protocol: layer2
      addresses:
        - 192.168.50.100-192.168.50.120

speaker:
  enabled: true
  frr:
    enabled: false
  frrk8s:
    enabled: false
  tolerateMaster: true

controller:
  enabled: true

prometheus:
  scrapeAnnotations: false
  serviceMonitor:
    enabled: false
  podMonitor:
    enabled: false

frr-k8s:
  enabled: false
  prometheus:
    serviceMonitor:
      enabled: false

frrk8s:
  enabled: false